name: Update store on tagging

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'korlibs/store.korge.org'
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Adds link to this repo
      run: ./addlink.main.kts https://github.com/${{ github.repository }}/tree/main/dummy
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.CREATE_STORE_PR_PAT }}


